### ISSUE TITLE
Drive Base

### ISSUE THREAD

**Issue by NathanGrenier** [sonic-howl/frc2024#15]
### 🚀 Summary:

Code Swerve Drive... reuse 2023 code. If phoenix6 api is not compatible use phoenix 5 and create new issue to update the firmware on the TalonFX (if possible).

### 📋 Tasks:

- [ ] Recover 2023 Swerve Drive
- [ ] Convert from ctre to phoenix5 or phoenix 6 api as needed.
- [ ] Make open loop control functional
- [ ] Recalibrate motor controllers with 2024 base.

**Comment by Portnord** [comment]
From line 165 swervesubsystem.py, and following two lines:   x = utils.utils.dz(self.controller.getForward()) * speed_scale
- x, y, z are all referring to undefined self,controller. We're almost certainly crashing out here and restarting into Disabled mode, Replace with the drive, strafe, turn parameters
- z should be run through dz (deadband) like x and y.
