### ISSUE TITLE
Launcher

### ISSUE THREAD

**Issue by Portnord** [sonic-howl/frc2024#20]
### 🚀 Summary:

Code the mechanism to launch or drop game pieces (notes) into scoring zones.

### 📋 Tasks:

- [ ] Create class for the shooter code.
- [ ] Create shooting function.
- [ ] Create unjam function.
- [ ] (Optional) Create function for raising and lowering shooter.
- [ ] Use drive team commands in robotpy to call new functions.

**Comment by Portnord** [comment]
Double check final decision for raising and lowering shooter, add appropriate functions. Note this may affect the controller mappings.
