### ISSUE TITLE
Roborio Camera Stream

### ISSUE THREAD

**Issue by Portnord** [sonic-howl/frc2024#25]
### 🚀 Summary:

Code the simplest camera stream from a USB camera and test for focal length. Python requires some slightly different use, see tasks for details.

### 📜 Tasks:

- [ ] Camera server initialization in myRobot, see: https://robotpy.readthedocs.io/projects/robotpy/en/stable/wpilib.cameraserver.html
- [ ] Add vision.py with simplest USB camera server 640x480 resolution, see: https://docs.wpilib.org/en/stable/docs/software/vision-processing/roborio/using-the-cameraserver-on-the-roborio.html
- [x] Test for focal length, both x and y axis (document here for now. Focal length (f) = screen image in pixels (i) x range/target size. Easiest to do by completely filling the display with an easily measured target.

**Comment by Portnord** [comment]
If the roborio installation is ok can try creating a simple vision.py file like in https://github.com/robotpy/examples/tree/main

**Comment by Portnord** [comment]
Current status:
- cscore.CameraServer.startAutomaticCapture() is the only functional way to launch the camera server so far.
- wpilib.cameraserver.CameraServer.launch(), the documented and recommended way of starting in python always launches a camera server that immediately aborts (errno -6).
- launch fails whether or not a vision.py is provided (does not appear to even be run)
- opening a shell to the roborio and manually executing the cscore process has the same effect as launching it within robot.py

Although the webstream is available with the current code, would still lik to troubleshoot why the recommended example code does not work.

**Comment by Portnord** [comment]
To move forward, use the startAutomaticCapture(). We need one forward facing camera and one rear facing camera, 640x480 resolution, FPS to adjust as needed. Will open a bug for the launch() function to be investigated.

**Comment by Portnord** [comment]
Feedback on Chief Delphi website from the robotpy developer was that using startAutomaticCapture should not cause issues when no vision processing is being done in the robot code.

Todo:
1) Check camera server settings on web browser, select best resolution and fps. See https://docs.wpilib.org/en/stable/docs/software/vision-processing/roborio/cameraserver-webserver.html
2) Restore commented code.
3) Record the focal length measurements from Monday.

**Comment by ColonelGuitar82** [comment]
Focal Lengths

C1 (Cam With Stand):  EST:625 EST:585
OFC (Logitech): EST:790 EST:825
ASS (No Stand): EST:625 EST:665
