### ISSUE TITLE
Drive Station Vision Processor

### ISSUE THREAD

**Issue by Portnord** [sonic-howl/frc2024#27]
### 🚀 Summary:

Create dashboard program to detect AprilTags and report robot position to roborio, Branch /mentor/portnord has an example of a functional (but not optimized) detector. An alternative to this task for the front camera is to use the limelight camera. A rear camera will still need to be made available for ring pickup.

### 📜 Tasks:

- [ ] Use openCV and wpilib apriltag module to detect tags in the roborio camera stream
- [ ] Compute the robot camera position and pose on the field of play
- [ ] Publish tag id, position and pose to network tables so roborio can use them.

**Comment by Portnord** [comment]
Was never integrated into bot. See branch mentor/portnord for an example of this.
