### ISSUE TITLE
Move to Pose

### ISSUE THREAD

**Issue by Portnord** [sonic-howl/frc2024#41]
### 🚀 Summary:

Add capability to command movement to a specific field location.

### 📜 Tasks:

- [x] Create swerve drive command to move to a specific pose, requires odometry and gyro.
- [x] Add button mappings to engage automated motion (e.g. shooting position, pickup location, amplifier)
- [x] Add robot.py logic to select destination pose and command drivebase.

**Comment by Portnord** [comment]
Correction to make: The field constants aren't correctly computing shooting distances. All distances in inches need to be added together before multiplying by the conversion to meters.

**Comment by Portnord** [comment]
Correction: The x and y inputs in the driveteam file should not be inverted for just red alliance inputs. They should invert only for red alliance input when we are in field oriented mode. Should probably be done in robot or swerve drive instead.

**Comment by Portnord** [comment]
Correction: Should force field oriented TPV when commanding move to pose

**Comment by Portnord** [comment]
Correction: Move to pose for pickups crashes, Rotation2D constructors need parentheses.

**Comment by Portnord** [comment]
Still testing, accidentally closed.
