### ISSUE TITLE
Limelight Camera

### ISSUE THREAD

**Issue by Portnord** [sonic-howl/frc2024#43]
### 🚀 Summary:

Use limelight to publish robot pose information to the roborio. This is an alternative to writing the drive station vision processing for the front camera. Note having both provides some redundancy in case the limelight fails.

### 📜 Tasks:

- [ ] Update the limelight for latest firmware
- [ ] Test apriltag detection and presence of pose information on network tables.
- [ ] Select a resolution and fps for competition.
- [ ] Compute focal lengths and field of view at selected resolution (useful for planning mounting).

**Comment by Portnord** [comment]
Neil has largely completed the first two tasks (to confirm).

**Comment by Portnord** [comment]
Limelight documentation for tag tracking starts here [Tracking AprilTags](https://docs.limelightvision.io/docs/docs-limelight/pipeline-apriltag/apriltags)

**Comment by Portnord** [comment]
Not done. To do next season.
