### ISSUE TITLE
Rear Camera Overlay

### ISSUE THREAD

**Issue by Portnord** [sonic-howl/frc2024#44]
### 🚀 Summary:

Add overlay to rear view camera to help guide driver to pickup notes. This can be predicted through geometry. Will require some dashboard vision processing.

### 📜 Tasks:

- [x] Define camera location in code constants. Initial choice of camera becomes arbitrary this way.
- [x] Use camera location to compute a projected path between the wheels that leads to the pickup.
- [x] Add paths to camera stream on drive station
